#!/bin/env bash

clear; ROKU_DEV_TARGET="$(echo 'grabing the ip!' 1>&2; nmap -sn 192.168.1.1/24 | grep 'SullysTv' | awk '{print $6}' | sed 's/(//; s/)//')"

clear; echo 'Roku'

dombo=1

asdf() {
while [ $dombo -le 2 ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/home"
  ((dombo=dombo+1))
done

dombo=1

sleep 2

while [ $dombo -le $sombo ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/right"
  ((dombo=dombo+1))
done

dombo=1

while [ $dombo -le $rombo ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/down"
  ((dombo=dombo+1))
done

curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/select"
dombo=1
}

fdsa() {
while [ $dombo -le 6 ]; do
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/up"
    sleep 1
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/up"
    sleep 2
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/down"
    sleep 1
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/down"
    sleep 2
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/left"
    sleep 1
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/right"
    sleep 2
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/left"
    sleep 1
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/right"
    sleep 5
    ((dombo=dombo+1))
done
sleep 115
curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/home"
sleep 60
curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/powerOff"
sleep 120
curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/powerOn"
sleep 10
curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/home"
sleep 1
dombo=1
while [ $dombo -le 3 ]; do
curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/right"
 ((dombo=dombo+1))
done
dombo=1
while [ $dombo -le 3 ]; do
curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/down"
 ((dombo=dombo+1))
done
curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/select"
dombo=1
}
force_m() {
while [ $dombo -le $forcem ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/volumedown"
  ((dombo=dombo+1))
done
dombo=1
}
turn_down() {
while [ $dombo -le 2 ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/home"
  ((dombo=dombo+1))
done
dombo=1
sleep 2
while [ $dombo -le 6 ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/down"
  ((dombo=dombo+1))
done
sleep 1
curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/select"
sleep 1
echo $lit | sed "s/./\0\n/g; s/|/%20/g; s/?/%3F/g; s/'/%27/g; s/,/%2C/g; s/\"/%22/g" | xargs -I {} curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/Lit_{}"
dombo=1
}
force_b() {
while [ $dombo -le 30 ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/backspace"
  ((dombo=dombo+1))
done
dombo=1
}
force_w() {
while [ $dombo -le $forcew ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/up"
  ((dombo=dombo+1))
done
dombo=1
}
force_s() {
while [ $dombo -le $forces ]; do
  curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/down"
  ((dombo=dombo+1))
done
dombo=1
}
force_a() {
  while [ $dombo -le $forcea ]; do
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/left"
    ((dombo=dombo+1))
  done
dombo=1
}
force_d() {
  while [ $dombo -le $forced ]; do
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/right"
    ((dombo=dombo+1))
  done
dombo=1
}
select_j() {
  while [ $dombo -le 2 ]; do
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/select"
    sleep 4
    ((dombo=dombo+1))
  done
dombo=1
}
force_h() {
  while [ $dombo -le $forceh ]; do
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/home"
    ((dombo=dombo+1))
  done
dombo=1
}
force_u() {
  while [ $dombo -le $forceu ]; do
    curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/volumeup"
    ((dombo=dombo+1))
  done
dombo=1
}
while read -r crack; do
  dumb='Roku'
  case "$crack" in
    w) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/up"
    ;;
    ww) read -p 'Number: ' -r forcew; force_w
    ;;
    s) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/down"
    ;;
    ss) read -p 'Number: ' -r forces; force_s 
    ;;
    a) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/left"
    ;;
    aa) read -p 'Number: ' -r forcea; force_a
    ;;
    d) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/right"
    ;;
    dd) read -p 'Number: ' -r forced; force_d
    ;;
    0) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/volumeup"
    ;;
    9) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/volumedown"
    ;;
    j) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/select"
    ;;
    jj) select_j
    ;;
    k) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/enter"
    ;;
    b) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/back"
    ;;
    h) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/home"
    ;;
    fh) read -p 'Number: ' -r forceh; force_h
    ;;
    m) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/volumemute"
    ;;
    t) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/search"
    ;;
    e) curl "http://$ROKU_DEV_TARGET:8060/query/media-player"; sleep 5
    ;;
    i) curl -s "http://$ROKU_DEV_TARGET:8060/query/device-info" > Roku-info.txt; clear; echo 'Saved info!' 1>&2; sleep 3
    ;;
    c) curl "http://$ROKU_DEV_TARGET:8060/query/chanperf"; sleep 5
    ;;
    l) read -p 'Keyboard: ' -r lit; echo $lit | sed "s/./\0\n/g; s/|/%20/g; s/?/%3F/g; s/'/%27/g; s/,/%2C/g; s/\"/%22/g" | xargs -I {} curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/Lit_{}"
    ;;
    pn) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/powerOn"
    ;;
    pf) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/powerOff"
    ;;
    ap) read -p 'Column: ' -r sombo; read -p 'Row: ' -r rombo; asdf
    ;;
    pr) fdsa
    ;;
    p) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/pause"
    ;;
    fm) read -p 'Number: ' -r forcem; force_m
    ;;
    fu) read -p 'Number: ' -r forceu; force_u
    ;;
    sm) read -p 'Say?: ' -r lit; turn_down
    ;;
    f) curl -d '' "http://$ROKU_DEV_TARGET:8060/keypress/backspace"
    ;;
    ff) force_b
    ;;
    sw) telnet towel.blinkenlights.nl
    ;;
    q) clear; exit 1
    ;;
    *) dumb="No dumb ass."
    ;;
  esac
  clear
  echo "$dumb"
done
exit 1
